
package Userdashboard;

import Transactions.CheckOUtSupplies;
import Transactions.RequestSupply;
import ababangui.LoginPage;
import ababangui.Supplies;
import javax.swing.JOptionPane;


public class UserDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lg = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ya = new javax.swing.JLabel();
        ya1 = new javax.swing.JLabel();
        ya3 = new javax.swing.JLabel();
        ya2 = new javax.swing.JLabel();
        acc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 59));

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DASHBOARD");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 290, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 130));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lg.setBackground(new java.awt.Color(255, 255, 255));
        lg.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        lg.setForeground(new java.awt.Color(255, 255, 255));
        lg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lg.setText("LOGOUT");
        lg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        lg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgMouseClicked(evt);
            }
        });
        jPanel2.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 170, 50));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 40, 50));

        ya.setBackground(new java.awt.Color(255, 255, 255));
        ya.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        ya.setForeground(new java.awt.Color(255, 255, 255));
        ya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ya.setText("SUPPLIES");
        ya.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        ya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yaMouseClicked(evt);
            }
        });
        jPanel2.add(ya, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 50));

        ya1.setBackground(new java.awt.Color(255, 255, 255));
        ya1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        ya1.setForeground(new java.awt.Color(255, 255, 255));
        ya1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ya1.setText("REQUEST A SUPPLY");
        ya1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        ya1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ya1MouseClicked(evt);
            }
        });
        jPanel2.add(ya1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 50));

        ya3.setBackground(new java.awt.Color(255, 255, 255));
        ya3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        ya3.setForeground(new java.awt.Color(255, 255, 255));
        ya3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ya3.setText("YOUR TRANSACTIONS");
        ya3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        ya3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ya3MouseClicked(evt);
            }
        });
        jPanel2.add(ya3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, 50));

        ya2.setBackground(new java.awt.Color(255, 255, 255));
        ya2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        ya2.setForeground(new java.awt.Color(255, 255, 255));
        ya2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ya2.setText("CHECK OUT SUPPLIES");
        ya2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        ya2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ya2MouseClicked(evt);
            }
        });
        jPanel2.add(ya2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 170, 50));

        acc.setBackground(new java.awt.Color(255, 255, 255));
        acc.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        acc.setForeground(new java.awt.Color(255, 255, 255));
        acc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc.setText("ACCOUNT");
        acc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accMouseClicked(evt);
            }
        });
        jPanel2.add(acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 170, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 995, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgMouseClicked
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "You have successfully logged out!", "Logout", JOptionPane.INFORMATION_MESSAGE);

            LoginPage li = new LoginPage();
            li.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_lgMouseClicked

    private void accMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accMouseClicked
        userAccounts uc = new userAccounts();
        uc.setVisible(true);
        this.dispose();

       
    }//GEN-LAST:event_accMouseClicked

    private void yaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yaMouseClicked
        userSupplies ua = new userSupplies();
        ua.setVisible(true);
        
        this.dispose();

   
    }//GEN-LAST:event_yaMouseClicked

    private void ya1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ya1MouseClicked
        RequestSupply rs = new RequestSupply();
        rs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ya1MouseClicked

    private void ya2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ya2MouseClicked
    CheckOUtSupplies cc = new CheckOUtSupplies();
    cc.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ya2MouseClicked

    private void ya3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ya3MouseClicked
       Yourtransactions yt = new Yourtransactions();
       yt.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ya3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lg;
    private javax.swing.JLabel ya;
    private javax.swing.JLabel ya1;
    private javax.swing.JLabel ya2;
    private javax.swing.JLabel ya3;
    // End of variables declaration//GEN-END:variables
}
