/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transactions;

import Userdashboard.UserDashboard;
import config.Logs;
import config.Session;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author II
 */
public class RequestSupply extends javax.swing.JFrame {

    /**
     * Creates new form RequestSupply
     */
    public RequestSupply() {
         setUndecorated(true);
        initComponents();
        loadSuppliesData();
    }
void loadSuppliesData() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); 

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supplytracker_db", "root", "");
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT supply_id, supply_name, description, quantity, unit, supplier_name, purchase_date, status FROM supplies");

        while (rs.next()) {
            model.addRow(new Object[] {
                rs.getInt("supply_id"),
                rs.getString("supply_name"),
                rs.getString("description"),
                rs.getInt("quantity"),
                rs.getString("unit"),
                rs.getString("supplier_name"),
                rs.getDate("purchase_date"),
                rs.getString("status")
            });
        }

        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading supplies: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        RequestSupply = new javax.swing.JButton();
        txtSupplyId = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Supply ID", "Name", "Description", "Quantity", "Unit"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, 850, 230));

        RequestSupply.setText("Request a supply");
        RequestSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestSupplyActionPerformed(evt);
            }
        });
        jPanel4.add(RequestSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 160, 70));
        jPanel4.add(txtSupplyId, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 310, 260, 50));
        jPanel4.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 310, 50));

        jLabel2.setText("Quantity:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 130, -1));

        jLabel3.setText("Enter the supply ID:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 130, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 870, 510));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 950, 550));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("'Request Supply'");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 700, 40));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 13, 70, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RequestSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestSupplyActionPerformed
      int supplyId;
    int quantity;

    try {
        supplyId = Integer.parseInt(txtSupplyId.getText().trim());
        quantity = Integer.parseInt(txtQuantity.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numeric values for Supply ID and Quantity.");
        return;
    }

    if (quantity <= 0) {
        JOptionPane.showMessageDialog(this, "Quantity must be greater than zero.");
        return;
    }

    int userId = Session.getInstance().getuid(); // Get user ID from session

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supplytracker_db", "root", "");

        // Check if supply exists and get current quantity
        String checkSupply = "SELECT quantity FROM supplies WHERE supply_id = ?";
        PreparedStatement psCheck = con.prepareStatement(checkSupply);
        psCheck.setInt(1, supplyId);
        ResultSet rsCheck = psCheck.executeQuery();

        if (!rsCheck.next()) {
            JOptionPane.showMessageDialog(this, "Supply ID not found.");
            con.close();
            return;
        }

        int currentQuantity = rsCheck.getInt("quantity");

        if (quantity > currentQuantity) {
            JOptionPane.showMessageDialog(this, "Not enough supply available. Current quantity: " + currentQuantity);
            con.close();
            return;
        }

        // Insert the request with 'pending' status
        String insertRequest = "INSERT INTO RequestedSuppliesUser (user_id, supply_id, quantity, status) VALUES (?, ?, ?, 'pending')";
        PreparedStatement pst = con.prepareStatement(insertRequest);
        pst.setInt(1, userId);
        pst.setInt(2, supplyId);
        pst.setInt(3, quantity);
        int rowsInserted = pst.executeUpdate();

        if (rowsInserted > 0) {
            // Deduct the quantity from the supplies table
            String updateSupply = "UPDATE supplies SET quantity = quantity - ? WHERE supply_id = ?";
            PreparedStatement psUpdate = con.prepareStatement(updateSupply);
            psUpdate.setInt(1, quantity);
            psUpdate.setInt(2, supplyId);
            psUpdate.executeUpdate();

            JOptionPane.showMessageDialog(this, "Supply request submitted. Awaiting admin approval.");
            txtSupplyId.setText("");
            txtQuantity.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to request supply.");
        }

        con.close();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
    }//GEN-LAST:event_RequestSupplyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       UserDashboard us = new UserDashboard();
       us.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestSupply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestSupply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestSupply;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSupplyId;
    // End of variables declaration//GEN-END:variables
}
